server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:6542/ewm-main
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=ewm
spring.datasource.password=ewm

spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

spring.sql.init.mode=always

spring.jackson.date-format=yyyy-MM-dd HH:mm:ss
spring.jackson.time-zone=UTC

stats-server.url=http://stats-server:9090
server.shutdown=graceful

logging.level.ru.practicum.ewm=debug
logging.level.org.springframework.transaction=info
logging.level.org.springframework.orm.jpa=info
